% function newstart=newstart(xx, ttheta, pp)
% newstart=[(1-ttheta)*(xx(1)+xx(11)),...
%           (1-ttheta)*(xx(2)+xx(12)),...
%     pp(1)*(1-ttheta)*(xx(3)+xx(13)+xx(4)),...
% (1-pp(1))*(1-ttheta)*(xx(3)+xx(13)+xx(4)),...
%     pp(1)*(1-ttheta)*(xx(5)+xx(14)+xx(6)),...
% (1-pp(1))*(1-ttheta)*(xx(5)+xx(14)+xx(6)),...
%       (1-ttheta)*(xx(7)+xx(15)),...
%       (1-ttheta)*(xx(8)+xx(16)),...
%       (1-ttheta)*(xx(9)+xx(17)),...
%       (1-ttheta)*(xx(10)+xx(18)),...     
%       ttheta*(xx(1)+xx(11)),...
%           ttheta*(xx(2)+xx(12)),...
%        ttheta*(xx(3)+xx(13)+xx(4)),...
%        ttheta*(xx(5)+xx(14)+xx(6)),...
%           ttheta*(xx(7)+xx(15)),...
%           ttheta*(xx(8)+xx(16)),...
%           ttheta*(xx(9)+xx(17)),...
%           ttheta*(xx(10)+xx(18))];

  
      function newstart=newstart(xx, ttheta, pp)
newstart=[(1-ttheta)*(xx(1)+xx(11)),...
          (1-ttheta)*(xx(2)+xx(12)),...
           0 ,...
          (1-ttheta)*(xx(3)+xx(13)+xx(4)),...
           0,...
          (1-ttheta)*(xx(5)+xx(14)+xx(6)),...
      (1-ttheta)*(xx(7)+xx(15)),...
      (1-ttheta)*(xx(8)+xx(16)),...
      (1-ttheta)*(xx(9)+xx(17)),...
      (1-ttheta)*(xx(10)+xx(18)),...     
      ttheta*(xx(1)+xx(11)),...
          ttheta*(xx(2)+xx(12)),...
       ttheta*(xx(3)+xx(13)+xx(4)),...
       ttheta*(xx(5)+xx(14)+xx(6)),...
          ttheta*(xx(7)+xx(15)),...
          ttheta*(xx(8)+xx(16)),...
          ttheta*(xx(9)+xx(17)),...
          ttheta*(xx(10)+xx(18))];